-- Caisse — SQLite schema (embedded, single-file DB).
-- Booleans are stored as INTEGER (0/1); timestamps as TEXT (ISO 8601).
-- Ids are TEXT, generated by the app. Money is integer minor units (whole MRU).

create table settings (
  id              integer primary key check (id = 1),
  spot_label      text not null default 'Table',
  currency_symbol text not null default 'MRU'
);

create table zones (
  zone_id       text primary key,
  name          text not null,
  display_order integer not null default 0,
  table_mode    text not null default 'free' check (table_mode in ('none','free','fixed')),
  spot_label    text,
  active        integer not null default 1
);

create table table_spots (
  table_id text primary key,
  zone_id  text not null references zones(zone_id),
  label    text not null,
  active   integer not null default 1
);

create table servers (
  server_id text primary key,
  name      text not null,
  active    integer not null default 1
);

create table shifts (
  shift_id   text primary key,
  name       text not null,
  start_time text not null,
  end_time   text not null
);

create table shift_assignments (
  assignment_id text primary key,
  server_id     text not null references servers(server_id),
  zone_id       text not null references zones(zone_id),
  shift_id      text not null references shifts(shift_id),
  date          text not null
);

create table categories (
  category_id   text primary key,
  name          text not null,
  color         text not null,
  display_order integer not null default 0
);

create table products (
  product_id  text primary key,
  name        text not null,
  category_id text not null references categories(category_id),
  price       integer not null default 0,
  active      integer not null default 1
);

create table modifiers (
  modifier_id text primary key,
  product_id  text not null references products(product_id),
  name        text not null,
  price_delta integer not null default 0,
  mod_group   text
);

create table reason_codes (
  reason_id text primary key,
  kind      text not null check (kind in ('void','comp','unpaid')),
  label     text not null,
  active    integer not null default 1
);

create table users (
  user_id  text primary key,
  name     text not null,
  pin_hash text not null,
  role     text not null default 'cashier' check (role in ('cashier','admin')),
  active   integer not null default 1
);

create table checks (
  check_id      text primary key,
  ticket_number integer not null,
  zone_id       text not null references zones(zone_id),
  server_id     text not null references servers(server_id),
  table_id      text,
  table_label   text,
  status        text not null default 'OPEN'
                  check (status in ('OPEN','IN_PROGRESS','CLOSED_PAID','CLOSED_UNPAID','VOIDED')),
  reason_id     text,
  opened_at     text not null,
  closed_at     text
);

create table order_items (
  item_id    text primary key,
  check_id   text not null references checks(check_id) on delete cascade,
  server_id  text not null,
  product_id text not null,
  name       text not null,
  qty        integer not null default 1,
  unit_price integer not null,
  state      text not null default 'HELD' check (state in ('HELD','SENT','VOID','COMP')),
  reason_id  text,
  created_at text not null
);

create table payments (
  payment_id text primary key,
  check_id   text not null references checks(check_id) on delete cascade,
  method     text not null,
  amount     integer not null,
  paid_at    text not null
);

create table audit_log (
  log_id    text primary key,
  actor_id  text,
  action    text not null,
  target    text not null,
  reason_id text,
  detail    text,
  timestamp text not null
);

create index idx_checks_status on checks (status);
create index idx_items_check on order_items (check_id);
create index idx_payments_check on payments (check_id);
create index idx_roster on shift_assignments (zone_id, shift_id, date);
